/**
 * Web: registers the service worker (public/sw.template.js → dist/sw.js,
 * generated by scripts/build-sw.mjs) so the app works offline once loaded,
 * and asks the browser not to evict our IndexedDB storage.
 * Only in production builds: in `expo start` the bundle changes constantly.
 */
export function enableOffline(): void {
  if (process.env.NODE_ENV !== 'production' || !('serviceWorker' in navigator)) return;
  const register = () => void navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch(() => undefined);
  // The bundle may run after the load event (deferred script + hydration).
  if (document.readyState === 'complete') register();
  else window.addEventListener('load', register, { once: true });
  void navigator.storage?.persist?.().catch(() => undefined);
}
